/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as SettingsRenderingRouteImport } from './routes/settings.rendering'
import { Route as ApiPublicRenderRouteImport } from './routes/api/public/render'
import { Route as ApiPublicRenderHealthRouteImport } from './routes/api/public/render-health'
import { Route as ApiPublicRenderDownloadIdRouteImport } from './routes/api/public/render-download.$id'
import { Route as ApiPublicRenderStatusIdRouteImport } from './routes/api/public/render-status.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRenderingRoute = SettingsRenderingRouteImport.update({
  id: '/settings/rendering',
  path: '/settings/rendering',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderRoute = ApiPublicRenderRouteImport.update({
  id: '/api/public/render',
  path: '/api/public/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderHealthRoute = ApiPublicRenderHealthRouteImport.update({
  id: '/api/public/render-health',
  path: '/api/public/render-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderDownloadIdRoute =
  ApiPublicRenderDownloadIdRouteImport.update({
    id: '/api/public/render-download/$id',
    path: '/api/public/render-download/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRenderStatusIdRoute = ApiPublicRenderStatusIdRouteImport.update({
  id: '/api/public/render-status/$id',
  path: '/api/public/render-status/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/brand': typeof BrandRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/editor/$id': typeof EditorIdRoute
  '/settings/rendering': typeof SettingsRenderingRoute
  '/api/public/render': typeof ApiPublicRenderRoute
  '/api/public/render-health': typeof ApiPublicRenderHealthRoute
  '/api/public/render-download/$id': typeof ApiPublicRenderDownloadIdRoute
  '/api/public/render-status/$id': typeof ApiPublicRenderStatusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/brand': typeof BrandRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/editor/$id': typeof EditorIdRoute
  '/settings/rendering': typeof SettingsRenderingRoute
  '/api/public/render': typeof ApiPublicRenderRoute
  '/api/public/render-health': typeof ApiPublicRenderHealthRoute
  '/api/public/render-download/$id': typeof ApiPublicRenderDownloadIdRoute
  '/api/public/render-status/$id': typeof ApiPublicRenderStatusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/brand': typeof BrandRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRoute
  '/editor/$id': typeof EditorIdRoute
  '/settings/rendering': typeof SettingsRenderingRoute
  '/api/public/render': typeof ApiPublicRenderRoute
  '/api/public/render-health': typeof ApiPublicRenderHealthRoute
  '/api/public/render-download/$id': typeof ApiPublicRenderDownloadIdRoute
  '/api/public/render-status/$id': typeof ApiPublicRenderStatusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced'
    | '/brand'
    | '/library'
    | '/projects'
    | '/editor/$id'
    | '/settings/rendering'
    | '/api/public/render'
    | '/api/public/render-health'
    | '/api/public/render-download/$id'
    | '/api/public/render-status/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced'
    | '/brand'
    | '/library'
    | '/projects'
    | '/editor/$id'
    | '/settings/rendering'
    | '/api/public/render'
    | '/api/public/render-health'
    | '/api/public/render-download/$id'
    | '/api/public/render-status/$id'
  id:
    | '__root__'
    | '/'
    | '/advanced'
    | '/brand'
    | '/library'
    | '/projects'
    | '/editor/$id'
    | '/settings/rendering'
    | '/api/public/render'
    | '/api/public/render-health'
    | '/api/public/render-download/$id'
    | '/api/public/render-status/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedRoute: typeof AdvancedRoute
  BrandRoute: typeof BrandRoute
  LibraryRoute: typeof LibraryRoute
  ProjectsRoute: typeof ProjectsRoute
  EditorIdRoute: typeof EditorIdRoute
  SettingsRenderingRoute: typeof SettingsRenderingRoute
  ApiPublicRenderRoute: typeof ApiPublicRenderRoute
  ApiPublicRenderHealthRoute: typeof ApiPublicRenderHealthRoute
  ApiPublicRenderDownloadIdRoute: typeof ApiPublicRenderDownloadIdRoute
  ApiPublicRenderStatusIdRoute: typeof ApiPublicRenderStatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rendering': {
      id: '/settings/rendering'
      path: '/settings/rendering'
      fullPath: '/settings/rendering'
      preLoaderRoute: typeof SettingsRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render': {
      id: '/api/public/render'
      path: '/api/public/render'
      fullPath: '/api/public/render'
      preLoaderRoute: typeof ApiPublicRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-health': {
      id: '/api/public/render-health'
      path: '/api/public/render-health'
      fullPath: '/api/public/render-health'
      preLoaderRoute: typeof ApiPublicRenderHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-download/$id': {
      id: '/api/public/render-download/$id'
      path: '/api/public/render-download/$id'
      fullPath: '/api/public/render-download/$id'
      preLoaderRoute: typeof ApiPublicRenderDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-status/$id': {
      id: '/api/public/render-status/$id'
      path: '/api/public/render-status/$id'
      fullPath: '/api/public/render-status/$id'
      preLoaderRoute: typeof ApiPublicRenderStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedRoute: AdvancedRoute,
  BrandRoute: BrandRoute,
  LibraryRoute: LibraryRoute,
  ProjectsRoute: ProjectsRoute,
  EditorIdRoute: EditorIdRoute,
  SettingsRenderingRoute: SettingsRenderingRoute,
  ApiPublicRenderRoute: ApiPublicRenderRoute,
  ApiPublicRenderHealthRoute: ApiPublicRenderHealthRoute,
  ApiPublicRenderDownloadIdRoute: ApiPublicRenderDownloadIdRoute,
  ApiPublicRenderStatusIdRoute: ApiPublicRenderStatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
