import type { Animation, Layout, Purpose, SurpriseKind, TextStyleName, Transition } from "./types";
import type { FontCategory } from "./fonts";
import type { LayoutGroupKey } from "./layouts";
import type { OverlayType } from "./types";

export interface Concept {
  key: string;
  /** short concept names, one is chosen per template */
  names: string[];
  idea: string;
  rhythms: string[];
  structure: Purpose[];
  layoutGroups: LayoutGroupKey[];
  layoutMotif: string;
  transitions: Transition[];
  transitionMotif: string;
  motionIn: Animation[];
  motionDuring: Animation[];
  visualMotif: string;
  fontCategories: FontCategory[];
  typographyMotif: string;
  textStyles: TextStyleName[];
  /** how many text moments at "moderate" typography */
  textBudget: number;
  textures: OverlayType[];
  surprises: SurpriseKind[];
  paletteIdx: number[];
  opening: string;
  middle: string;
  ending: string;
  restraint: string[];
  aesthetics: string[];
}

export const CONCEPTS: Concept[] = [
  {
    key: "kinetic_trail",
    names: ["KINETIC TRAIL", "MOTION LINE", "FORWARD DRIVE", "CHASE"],
    idea: "Movement-led edit that begins with an aggressive burst, opens into space, and resolves into a restrained hero frame.",
    rhythms: ["microcut_open", "build_release", "accelerating"],
    structure: ["hook", "detail", "product", "lifestyle", "hero"],
    layoutGroups: ["full", "panels", "threeUp"],
    layoutMotif: "frames expanding into full screen",
    transitions: ["whip", "directional_blur", "expand_frame", "hard_cut", "punch_zoom"],
    transitionMotif: "directional motion and frame expansion",
    motionIn: ["snap_move", "expand", "punch_in", "slide_left"],
    motionDuring: ["pan_right", "aggressive_push_in", "drift"],
    visualMotif: "everything travels in one direction",
    fontCategories: ["Bold / Condensed"],
    typographyMotif: "large condensed words appearing only three times",
    textStyles: ["giant_word", "oversized_hook", "edge_aligned", "cta_lockup"],
    textBudget: 3,
    textures: ["grain", "halation"],
    surprises: ["three_shot_burst", "frame_within_frame", "abrupt_scale"],
    paletteIdx: [0, 4, 5],
    opening: "three-shot movement burst",
    middle: "spacious lifestyle frames",
    ending: "held product hero",
    restraint: ["no more than two major effects at once", "typography appears at most three times"],
    aesthetics: ["Sport", "Cinematic", "Clean", "Experimental"],
  },
  {
    key: "editorial_product",
    names: ["EDITORIAL PRODUCT", "MARGIN", "FOLIO", "QUIET OBJECT"],
    idea: "Whitespace-driven layout study with asymmetric frames and restrained serif typography.",
    rhythms: ["slow_fast_slow", "breathing_middle", "alternating"],
    structure: ["lifestyle", "detail", "product", "hero"],
    layoutGroups: ["panels", "framed", "verticalSplit", "full"],
    layoutMotif: "asymmetric frames inside generous margins",
    transitions: ["mask_wipe", "hard_cut", "blur", "collapse_frame"],
    transitionMotif: "quiet wipes, mostly cuts",
    motionIn: ["mask_reveal", "slow_push_in", "expand"],
    motionDuring: ["slow_push_in", "drift", "none"],
    visualMotif: "the frame is a page",
    fontCategories: ["Editorial", "Luxury"],
    typographyMotif: "restrained serif captions with real hierarchy",
    textStyles: ["centered_statement", "minimal_caption", "masked_reveal", "tracking_in"],
    textBudget: 3,
    textures: ["paper", "frame_line"],
    surprises: ["typography_takeover", "layout_collapse", "unexpected_pause"],
    paletteIdx: [3, 1, 2],
    opening: "single quiet establishing frame",
    middle: "asymmetric split study",
    ending: "centred product on whitespace",
    restraint: ["never more than two frames on screen", "no flashes, no grain"],
    aesthetics: ["Editorial", "Luxury", "Clean", "Fashion"],
  },
  {
    key: "micro_burst",
    names: ["MICRO BURST", "STROBE", "SNAP STACK", "RAPID"],
    idea: "Extremely rapid cuts alternating macro detail with full shots, almost no typography.",
    rhythms: ["rapid_burst", "double_hit", "triple_hit"],
    structure: ["detail", "product", "detail", "hook", "hero"],
    layoutGroups: ["full", "quad"],
    layoutMotif: "full screen with brief 2x2 hits",
    transitions: ["hard_cut", "flash", "snap_zoom_out", "punch_zoom", "rgb_split"],
    transitionMotif: "hard cuts with occasional flash frames",
    motionIn: ["snap_zoom", "punch_in", "rotate_snap"],
    motionDuring: ["none", "push_in"],
    visualMotif: "impact over elegance",
    fontCategories: ["Bold / Condensed", "Technical"],
    typographyMotif: "one word, twice, that's it",
    textStyles: ["giant_word", "word_by_word", "cta_lockup"],
    textBudget: 2,
    textures: ["grain", "chromatic"],
    surprises: ["freeze_frame", "giant_word", "three_shot_burst"],
    paletteIdx: [0, 5, 4],
    opening: "four micro shots before the viewer settles",
    middle: "macro / wide alternation",
    ending: "abrupt hero freeze",
    restraint: ["text never overlaps a transition", "no layered layouts during bursts"],
    aesthetics: ["Raw", "Sport", "Experimental", "Playful"],
  },
  {
    key: "film_contact",
    names: ["FILM CONTACT", "CONTACT SHEET", "SPLICE", "NEGATIVE"],
    idea: "Tactile film-strip and contact-sheet aesthetic with a slower, deliberate rhythm.",
    rhythms: ["decelerating", "alternating", "hero_hold"],
    structure: ["lifestyle", "detail", "proof", "product", "hero"],
    layoutGroups: ["filmStrip", "contactSheet", "full"],
    layoutMotif: "strips and sheets assembling into one frame",
    transitions: ["film_splice", "hard_cut", "mask_wipe", "blur"],
    transitionMotif: "splice jumps like a physical cut",
    motionIn: ["expand", "handheld", "slow_push_in"],
    motionDuring: ["handheld", "drift", "none"],
    visualMotif: "photographic, tactile, printed",
    fontCategories: ["Technical", "Retro", "Editorial"],
    typographyMotif: "small technical captions like sheet annotations",
    textStyles: ["subtitle", "minimal_caption", "vertical_type", "cta_lockup"],
    textBudget: 3,
    textures: ["grain", "film_border", "light_leak", "timestamp"],
    surprises: ["film_strip", "freeze_frame", "unexpected_pause"],
    paletteIdx: [1, 3, 0],
    opening: "a single frame like a contact print",
    middle: "sheet of frames filling in",
    ending: "one frame enlarged and held",
    restraint: ["only one texture beyond grain", "no kinetic typography"],
    aesthetics: ["Retro", "Raw", "Editorial", "Cinematic"],
  },
  {
    key: "type_takeover",
    names: ["TYPE TAKEOVER", "WORD STACK", "LOUD", "SHOUT"],
    idea: "Typography is the lead actor; footage plays behind and between the words.",
    rhythms: ["fast_slow_fast", "double_hit", "build_release"],
    structure: ["hook", "product", "proof", "hero"],
    layoutGroups: ["full", "horizontalSplit", "stacked"],
    layoutMotif: "banded frames carrying type",
    transitions: ["hard_cut", "stretch", "smear", "flash"],
    transitionMotif: "type-driven smears and stretches",
    motionIn: ["punch_in", "slide_up", "smear_in"],
    motionDuring: ["push_in", "none"],
    visualMotif: "words interrupt the image",
    fontCategories: ["Bold / Condensed", "Playful"],
    typographyMotif: "word-by-word takeover with one giant payoff",
    textStyles: ["word_by_word", "giant_word", "outlined", "highlight_bar", "cta_lockup"],
    textBudget: 5,
    textures: ["grain", "bloom"],
    surprises: ["typography_takeover", "giant_word", "abrupt_scale"],
    paletteIdx: [4, 0, 5],
    opening: "one word before any footage reads",
    middle: "alternating word and image",
    ending: "CTA lockup on hero",
    restraint: ["one typographic idea only", "no split layouts under type"],
    aesthetics: ["Playful", "Raw", "Sport", "Experimental"],
  },
  {
    key: "lux_slow",
    names: ["SLOW LUXE", "VELVET", "ATELIER", "PATIENCE"],
    idea: "Long, still frames with almost imperceptible motion and luxury typography.",
    rhythms: ["decelerating", "hero_hold", "breathing_middle"],
    structure: ["lifestyle", "detail", "product", "hero"],
    layoutGroups: ["full", "framed"],
    layoutMotif: "full frame with one bordered inset moment",
    transitions: ["blur", "hard_cut", "mask_wipe"],
    transitionMotif: "soft dissolvent blurs, sparingly",
    motionIn: ["slow_push_in", "mask_reveal"],
    motionDuring: ["slow_push_in", "drift"],
    visualMotif: "stillness and light",
    fontCategories: ["Luxury", "Editorial"],
    typographyMotif: "wide-tracked capitals appearing twice",
    textStyles: ["tracking_in", "centered_statement", "minimal_caption", "cta_lockup"],
    textBudget: 2,
    textures: ["halation", "vignette", "bloom"],
    surprises: ["unexpected_pause", "frame_within_frame"],
    paletteIdx: [1, 3, 2],
    opening: "slow push on a detail",
    middle: "held lifestyle frame",
    ending: "product centred, type tracks in",
    restraint: ["never cut faster than one second", "one accent colour only"],
    aesthetics: ["Luxury", "Cinematic", "Clean", "Fashion"],
  },
  {
    key: "grid_system",
    names: ["GRID SYSTEM", "MODULE", "SWISS", "ORDER"],
    idea: "A composed grid that fills in, rearranges, then collapses into a single hero frame.",
    rhythms: ["alternating", "build_release", "slow_fast_slow"],
    structure: ["detail", "lifestyle", "product", "proof", "hero"],
    layoutGroups: ["quad", "threeUp", "mosaic", "full"],
    layoutMotif: "grid modules populating and collapsing",
    transitions: ["collapse_frame", "expand_frame", "hard_cut", "mask_wipe"],
    transitionMotif: "modules snapping in and out",
    motionIn: ["expand", "slide_up", "collapse"],
    motionDuring: ["slow_push_in", "none"],
    visualMotif: "structure you can read",
    fontCategories: ["Minimal", "Technical"],
    typographyMotif: "small labelled captions inside the system",
    textStyles: ["minimal_caption", "feature_callout", "stat_callout", "cta_lockup"],
    textBudget: 4,
    textures: ["frame_line", "noise"],
    surprises: ["layout_collapse", "split_screen", "frame_within_frame"],
    paletteIdx: [2, 3, 0],
    opening: "one module lands",
    middle: "the full grid resolves",
    ending: "grid collapses to hero",
    restraint: ["grid never mixes with floating frames", "one caption per module"],
    aesthetics: ["Clean", "Editorial", "Experimental", "Fashion"],
  },
  {
    key: "raw_camcorder",
    names: ["HANDHELD", "TAPE", "FOUND FOOTAGE", "VHS RUN"],
    idea: "Deliberately raw handheld feel with camcorder furniture and imperfect framing.",
    rhythms: ["fake_pause", "alternating", "microcut_open"],
    structure: ["hook", "lifestyle", "detail", "product", "hero"],
    layoutGroups: ["full", "overlapping"],
    layoutMotif: "single handheld frame, occasional overlap",
    transitions: ["film_splice", "hard_cut", "rgb_split", "blur_pulse"],
    transitionMotif: "tape-like jumps",
    motionIn: ["handheld", "snap_move", "punch_in"],
    motionDuring: ["handheld", "drift"],
    visualMotif: "imperfection as authenticity",
    fontCategories: ["Technical", "Retro"],
    typographyMotif: "monospace burn-in captions",
    textStyles: ["subtitle", "ticker", "minimal_caption", "cta_lockup"],
    textBudget: 3,
    textures: ["camcorder", "timestamp", "noise", "chromatic"],
    surprises: ["freeze_frame", "unexpected_pause", "split_screen"],
    paletteIdx: [0, 4, 2],
    opening: "camera already running",
    middle: "loose handheld coverage",
    ending: "abrupt tape stop on hero",
    restraint: ["no clean typography", "no grid layouts"],
    aesthetics: ["Raw", "Retro", "Playful", "Sport"],
  },
  {
    key: "proof_stack",
    names: ["PROOF STACK", "CLAIM", "RECEIPTS", "DIRECT"],
    idea: "Performance-ad logic: hook, benefit, proof numbers, CTA — clean and legible throughout.",
    rhythms: ["hero_hold", "accelerating", "alternating"],
    structure: ["hook", "product", "proof", "hero"],
    layoutGroups: ["full", "horizontalSplit", "floating"],
    layoutMotif: "full screen with a supporting inset for proof",
    transitions: ["hard_cut", "push_out", "flash", "punch_zoom"],
    transitionMotif: "mostly cuts, one push",
    motionIn: ["push_in", "slide_up", "punch_in"],
    motionDuring: ["push_in", "none"],
    visualMotif: "clarity over craft",
    fontCategories: ["Minimal", "Bold / Condensed"],
    typographyMotif: "claims, numbers, CTA — always legible",
    textStyles: ["oversized_hook", "highlight_bar", "stat_callout", "cta_lockup"],
    textBudget: 4,
    textures: ["progress"],
    surprises: ["giant_word", "split_screen", "abrupt_scale"],
    paletteIdx: [0, 2, 5],
    opening: "hook stated in the first second",
    middle: "benefit then proof",
    ending: "CTA held for a full beat",
    restraint: ["never obscure the product with type", "one effect per shot"],
    aesthetics: ["Clean", "Sport", "Playful", "Cinematic"],
  },
  {
    key: "collage_cut",
    names: ["COLLAGE CUT", "PASTE UP", "SCRAPBOOK", "OVERLAP"],
    idea: "Overlapping frames pasted over each other, building a layered composition that resolves.",
    rhythms: ["build_release", "triple_hit", "breathing_middle"],
    structure: ["hook", "detail", "lifestyle", "product", "hero"],
    layoutGroups: ["overlapping", "contactSheet", "full"],
    layoutMotif: "frames pasted over frames",
    transitions: ["hard_cut", "shape_wipe", "stretch", "collapse_frame"],
    transitionMotif: "shapes cutting into shapes",
    motionIn: ["scale_bounce", "rotate_snap", "expand"],
    motionDuring: ["float", "subtle_rotate"],
    visualMotif: "layers with visible edges",
    fontCategories: ["Playful", "Retro", "Bold / Condensed"],
    typographyMotif: "cut-out words placed like stickers",
    textStyles: ["outlined", "highlight_bar", "kinetic_words", "cta_lockup"],
    textBudget: 4,
    textures: ["paper", "grain", "posterize"],
    surprises: ["layout_collapse", "frame_within_frame", "typography_takeover"],
    paletteIdx: [5, 4, 1],
    opening: "one frame lands off-centre",
    middle: "layers accumulate",
    ending: "everything collapses into one frame",
    restraint: ["max three layers at once", "one rotation angle reused"],
    aesthetics: ["Playful", "Retro", "Experimental", "Fashion"],
  },
];

export const conceptByKey = (key: string) => CONCEPTS.find((c) => c.key === key) ?? CONCEPTS[0]!;
