import type { MediaSlot, TemplateSpec, TextSlot } from "./types";

const PAL = {
  ember: { bg: "#0b0b0c", ink: "#f7f4ef", accent: "#ff5722" },
  sand: { bg: "#efe9df", ink: "#17150f", accent: "#c2410c" },
  night: { bg: "#08090c", ink: "#ffffff", accent: "#7dd3fc" },
  paper: { bg: "#f5f3ee", ink: "#111111", accent: "#111111" },
  acid: { bg: "#0d0f08", ink: "#f2ffd6", accent: "#d7ff36" },
};

const m = (
  i: number,
  start: number,
  duration: number,
  purpose: MediaSlot["purpose"],
  label: string,
  rest: Partial<MediaSlot> = {},
): MediaSlot => ({
  id: `slot_${String(i).padStart(2, "0")}`,
  label,
  start,
  duration,
  purpose,
  layout: "full",
  animationIn: "punch_in",
  transitionOut: "hard_cut",
  ...rest,
});

const t = (
  i: number,
  label: string,
  value: string,
  start: number,
  duration: number,
  rest: Partial<TextSlot> = {},
): TextSlot => ({
  id: `text_${String(i).padStart(2, "0")}`,
  label,
  value,
  start,
  duration,
  style: "minimal_caption",
  position: "bottom",
  ...rest,
});

export const RAPID_PRODUCT: TemplateSpec = {
  id: "rapid-product",
  name: "RAPID PRODUCT",
  duration: 8,
  fps: 30,
  width: 1080,
  height: 1920,
  tags: ["Footwear", "Product", "Performance Ads"],
  palette: PAL.ember,
  beatMarkers: [0, 0.4, 0.75, 1.1, 1.5, 2.2, 3, 4, 5, 6, 7],
  creativeProfile: {
    family: "Rapid Product",
    energy: "Aggressive",
    pacing: "rapid burst → breathing moment → hero",
    typography: "oversized hook + feature callouts",
    transitionStyle: "flash / snap zoom / hard cut",
    structure: "hook → product → detail → proof → hero",
  },
  mediaSlots: [
    m(1, 0, 0.4, "hook", "HOOK", { animationIn: "snap_zoom", transitionOut: "flash" }),
    m(2, 0.4, 0.35, "detail", "DETAIL", { animationIn: "slide_left", transitionOut: "hard_cut" }),
    m(3, 0.75, 0.35, "product", "PRODUCT", { animationIn: "punch_in", transitionOut: "whip" }),
    m(4, 1.1, 0.4, "detail", "DETAIL", { animationIn: "slide_up", transitionOut: "flash" }),
    m(5, 1.5, 0.7, "lifestyle", "LIFESTYLE", { animationIn: "push_in", animationDuring: "drift", transitionOut: "blur" }),
    m(6, 2.2, 0.8, "product", "PRODUCT", { animationIn: "pull_out", transitionOut: "hard_cut" }),
    m(7, 3, 1, "detail", "TEXTURE", { animationIn: "pan_left", transitionOut: "wipe_left" }),
    m(8, 4, 1.2, "proof", "PROOF", { animationIn: "punch_in", animationDuring: "drift", transitionOut: "flash" }),
    m(9, 5.2, 0.8, "lifestyle", "MOTION", { animationIn: "slide_right", transitionOut: "whip" }),
    m(10, 6, 2, "hero", "HERO", { animationIn: "push_in", animationDuring: "drift", transitionOut: "hard_cut" }),
  ],
  textSlots: [
    t(1, "HOOK", "BUILT TO MOVE", 0.15, 1.35, { style: "oversized_hook", position: "center", accent: true }),
    t(2, "FEATURE", "LIGHTER. FASTER.", 2.3, 1.4, { style: "feature_callout", position: "bottom", align: "left" }),
    t(3, "PROOF", "40% MORE REBOUND", 4.1, 1.1, { style: "kinetic_words", position: "center" }),
    t(4, "CTA", "SHOP NOW", 6.4, 1.6, { style: "cta_lockup", position: "bottom", accent: true }),
  ],
  overlays: [
    { type: "flash", start: 0.4, duration: 0.12 },
    { type: "flash", start: 1.1, duration: 0.12 },
    { type: "flash", start: 5.2, duration: 0.1, accent: true },
    { type: "grain", start: 0, duration: 8 },
    { type: "progress", start: 0, duration: 8, accent: true },
  ],
};

export const KINETIC_TYPE: TemplateSpec = {
  id: "kinetic-type",
  name: "KINETIC TYPE",
  duration: 10,
  fps: 30,
  width: 1080,
  height: 1920,
  tags: ["Fashion", "Product", "Performance Ads"],
  palette: PAL.acid,
  beatMarkers: [0, 0.5, 1, 1.5, 2.5, 3.5, 4.5, 6, 7.5, 9],
  creativeProfile: {
    family: "Kinetic",
    energy: "Energetic",
    pacing: "rhythmic hard cuts on the beat",
    typography: "kinetic words, staggered reveals",
    transitionStyle: "whip / wipe / scale",
    structure: "text hook → visual proof → CTA",
  },
  mediaSlots: [
    m(1, 0, 0.5, "hook", "HOOK", { animationIn: "expand", transitionOut: "wipe_up" }),
    m(2, 0.5, 0.5, "detail", "DETAIL", { animationIn: "slide_up", transitionOut: "whip" }),
    m(3, 1, 0.5, "product", "PRODUCT", { animationIn: "snap_zoom", transitionOut: "hard_cut" }),
    m(4, 1.5, 1, "lifestyle", "LIFESTYLE", { animationIn: "pan_right", transitionOut: "scale_out" }),
    m(5, 2.5, 1, "detail", "DETAIL", { animationIn: "punch_in", transitionOut: "whip" }),
    m(6, 3.5, 1, "product", "PRODUCT", { animationIn: "slide_left", transitionOut: "hard_cut" }),
    m(7, 4.5, 1.5, "proof", "PROOF", { animationIn: "push_in", animationDuring: "drift", transitionOut: "wipe_left" }),
    m(8, 6, 1.5, "lifestyle", "MOTION", { animationIn: "pan_left", transitionOut: "whip" }),
    m(9, 7.5, 2.5, "hero", "HERO", { animationIn: "punch_in", animationDuring: "drift" }),
    m(10, 2.5, 1, "detail", "INSET", { layout: "pip", animationIn: "scale_bounce", transform: { rotation: -4 } }),
    m(11, 6, 1.5, "product", "FLOATING", { layout: "floating", animationIn: "slide_right", transform: { rotation: 3 } }),
  ],
  textSlots: [
    t(1, "HOOK", "STOP SCROLLING", 0.1, 1.4, { style: "kinetic_words", position: "center", accent: true }),
    t(2, "LINE 2", "THIS CHANGES EVERYTHING", 1.6, 1.6, { style: "stagger_reveal", position: "center" }),
    t(3, "BENEFIT", "ALL DAY COMFORT", 3.6, 1.6, { style: "edge_aligned", position: "top", align: "left" }),
    t(4, "PROOF", "10,000 5-STAR REVIEWS", 5, 1.4, { style: "feature_callout", position: "bottom" }),
    t(5, "CTA", "TAP TO SHOP", 8, 2, { style: "cta_lockup", position: "center", accent: true }),
  ],
  overlays: [
    { type: "bar_wipe", start: 1.5, duration: 0.3, accent: true },
    { type: "bar_wipe", start: 4.5, duration: 0.3 },
    { type: "flash", start: 7.5, duration: 0.12, accent: true },
    { type: "grain", start: 0, duration: 10 },
    { type: "progress", start: 0, duration: 10, accent: true },
  ],
};

export const EDITORIAL_SPLIT: TemplateSpec = {
  id: "editorial-split",
  name: "EDITORIAL SPLIT",
  duration: 12,
  fps: 30,
  width: 1080,
  height: 1920,
  tags: ["Fashion", "Beauty", "Lifestyle"],
  palette: PAL.paper,
  beatMarkers: [0, 1.5, 3, 4.5, 6, 8, 10],
  creativeProfile: {
    family: "Editorial",
    energy: "Minimal",
    pacing: "slow-fast-slow with whitespace",
    typography: "edge-aligned, restrained",
    transitionStyle: "wipes and mask reveals",
    structure: "lifestyle → details → product hero",
  },
  mediaSlots: [
    m(1, 0, 2, "hook", "OPENING", { animationIn: "mask_reveal", animationDuring: "drift", transitionOut: "wipe_up" }),
    m(2, 2, 2, "lifestyle", "SPLIT LEFT", { layout: "split-left", animationIn: "slide_left" }),
    m(3, 2, 2, "detail", "SPLIT RIGHT", { layout: "split-right", animationIn: "slide_right" }),
    m(4, 4, 1.5, "detail", "TOP FRAME", { layout: "split-top", animationIn: "slide_down" }),
    m(5, 4, 1.5, "product", "BOTTOM FRAME", { layout: "split-bottom", animationIn: "slide_up" }),
    m(6, 5.5, 2.5, "lifestyle", "BREATH", { animationIn: "push_in", animationDuring: "drift", transitionOut: "blur" }),
    m(7, 8, 1.3, "detail", "GRID 1", { layout: "grid-tl", animationIn: "scale_bounce" }),
    m(8, 8, 1.3, "detail", "GRID 2", { layout: "grid-tr", animationIn: "scale_bounce" }),
    m(9, 8, 1.3, "product", "GRID 3", { layout: "grid-bl", animationIn: "scale_bounce" }),
    m(10, 8, 1.3, "proof", "GRID 4", { layout: "grid-br", animationIn: "scale_bounce" }),
    m(11, 9.3, 2.7, "hero", "HERO", { animationIn: "expand", animationDuring: "drift" }),
  ],
  textSlots: [
    t(1, "HOOK", "the everyday edit", 0.4, 1.6, { style: "centered_statement", position: "center" }),
    t(2, "CAPTION", "01 — form", 2.2, 1.6, { style: "minimal_caption", position: "bottom", align: "left" }),
    t(3, "CAPTION 2", "02 — function", 4.2, 1.3, { style: "minimal_caption", position: "top", align: "right" }),
    t(4, "STATEMENT", "MADE FOR THE LONG WALK", 6, 2, { style: "masked_reveal", position: "center" }),
    t(5, "CTA", "in stores now", 10, 2, { style: "cta_lockup", position: "bottom" }),
  ],
  overlays: [
    { type: "frame_line", start: 0, duration: 12 },
    { type: "bar_wipe", start: 2, duration: 0.4 },
    { type: "vignette", start: 0, duration: 12 },
  ],
};

export const LIFESTYLE_BUILD: TemplateSpec = {
  id: "lifestyle-build",
  name: "LIFESTYLE BUILD",
  duration: 15,
  fps: 30,
  width: 1080,
  height: 1920,
  tags: ["Outdoor", "Lifestyle", "Beverage"],
  palette: PAL.sand,
  beatMarkers: [0, 2, 4, 6, 8, 10, 12, 14],
  creativeProfile: {
    family: "Cinematic",
    energy: "Cinematic",
    pacing: "long shots, build and release",
    typography: "restrained captions",
    transitionStyle: "blur and scale",
    structure: "lifestyle → details → product hero → CTA",
  },
  mediaSlots: [
    m(1, 0, 2.6, "lifestyle", "ESTABLISH", { animationIn: "push_in", animationDuring: "drift", transitionOut: "blur" }),
    m(2, 2.6, 2.2, "detail", "DETAIL", { animationIn: "pan_right", animationDuring: "drift", transitionOut: "blur" }),
    m(3, 4.8, 2.2, "lifestyle", "HUMAN", { animationIn: "pull_out", animationDuring: "drift", transitionOut: "hard_cut" }),
    m(4, 7, 0.5, "detail", "MICRO 1", { animationIn: "punch_in", transitionOut: "flash" }),
    m(5, 7.5, 0.5, "product", "MICRO 2", { animationIn: "snap_zoom", transitionOut: "flash" }),
    m(6, 8, 0.5, "detail", "MICRO 3", { animationIn: "slide_left", transitionOut: "flash" }),
    m(7, 8.5, 2.5, "proof", "RELEASE", { animationIn: "push_in", animationDuring: "drift", transitionOut: "scale_out" }),
    m(8, 11, 4, "hero", "PRODUCT HERO", { animationIn: "mask_reveal", animationDuring: "drift" }),
    m(9, 4.8, 2.2, "detail", "INSET", { layout: "tall-inset", animationIn: "slide_up" }),
  ],
  textSlots: [
    t(1, "HOOK", "some mornings ask for more", 0.6, 2, { style: "minimal_caption", position: "bottom", align: "left" }),
    t(2, "BENEFIT", "ALL TERRAIN. ALL DAY.", 5, 2, { style: "stagger_reveal", position: "top", align: "left" }),
    t(3, "STATEMENT", "GO FURTHER", 9, 1.8, { style: "centered_statement", position: "center", accent: true }),
    t(4, "CTA", "EXPLORE THE RANGE", 12.6, 2.4, { style: "cta_lockup", position: "bottom", accent: true }),
  ],
  overlays: [
    { type: "grain", start: 0, duration: 15 },
    { type: "vignette", start: 0, duration: 15 },
    { type: "flash", start: 7, duration: 0.1 },
    { type: "progress", start: 0, duration: 15 },
  ],
};

export const PRODUCT_REVEAL: TemplateSpec = {
  id: "product-reveal",
  name: "PRODUCT REVEAL",
  duration: 10,
  fps: 30,
  width: 1080,
  height: 1920,
  tags: ["Footwear", "Product", "Beauty"],
  palette: PAL.night,
  beatMarkers: [0, 0.6, 1.2, 1.8, 2.4, 3.6, 5, 6.5, 8],
  creativeProfile: {
    family: "Performance Ad",
    energy: "Energetic",
    pacing: "build → burst → hero hold",
    typography: "masked reveals + CTA lockup",
    transitionStyle: "mask reveal / scale",
    structure: "build → burst → hero",
  },
  mediaSlots: [
    m(1, 0, 0.6, "hook", "TEASE 1", { layout: "band", animationIn: "expand", transitionOut: "mask_out" }),
    m(2, 0.6, 0.6, "detail", "TEASE 2", { layout: "band", animationIn: "slide_left", transitionOut: "mask_out" }),
    m(3, 1.2, 0.6, "detail", "TEASE 3", { layout: "band", animationIn: "slide_right", transitionOut: "mask_out" }),
    m(4, 1.8, 0.3, "product", "BURST 1", { animationIn: "snap_zoom", transitionOut: "flash" }),
    m(5, 2.1, 0.3, "detail", "BURST 2", { animationIn: "punch_in", transitionOut: "flash" }),
    m(6, 2.4, 0.3, "product", "BURST 3", { animationIn: "slide_up", transitionOut: "flash" }),
    m(7, 2.7, 0.9, "lifestyle", "SETTLE", { animationIn: "pull_out", transitionOut: "blur" }),
    m(8, 3.6, 1.4, "detail", "MACRO", { animationIn: "pan_left", animationDuring: "drift", transitionOut: "scale_out" }),
    m(9, 5, 1.5, "proof", "PROOF", { animationIn: "push_in", transitionOut: "wipe_up" }),
    m(10, 6.5, 3.5, "hero", "HERO HOLD", { animationIn: "mask_reveal", animationDuring: "drift" }),
  ],
  textSlots: [
    t(1, "TEASE", "SOMETHING NEW", 0.2, 1.5, { style: "masked_reveal", position: "center" }),
    t(2, "HOOK", "ENGINEERED LIGHT", 2.8, 1.6, { style: "oversized_hook", position: "center", accent: true }),
    t(3, "FEATURE", "AIR-CORE MIDSOLE", 4.4, 1.5, { style: "feature_callout", position: "bottom", align: "left" }),
    t(4, "CTA", "AVAILABLE NOW", 7.2, 2.8, { style: "cta_lockup", position: "bottom", accent: true }),
  ],
  overlays: [
    { type: "flash", start: 1.8, duration: 0.14, accent: true },
    { type: "flash", start: 2.4, duration: 0.1 },
    { type: "bar_wipe", start: 6.5, duration: 0.4, accent: true },
    { type: "grain", start: 0, duration: 10 },
    { type: "progress", start: 0, duration: 10, accent: true },
  ],
};

export const BASE_TEMPLATES: TemplateSpec[] = [
  RAPID_PRODUCT,
  KINETIC_TYPE,
  EDITORIAL_SPLIT,
  LIFESTYLE_BUILD,
  PRODUCT_REVEAL,
];